import test from "node:test";
import assert from "node:assert/strict";

import { finalAgentOutput, finalRepairOutput, finalReviewOutput } from "../src/agent-output.js";

test("PR reviews publish only the final verdict block", () => {
  const transcript = [
    "I'll review this as pass 1 against the plan contract.",
    "[mcp] crew.plan_read (completed)",
    "Plan evidence is loaded. I am checking the local branch.",
    "[cmd] /bin/bash -lc 'git diff --stat main...HEAD'",
    "The source largely matches the contract; I am running tests.",
    "[cmd] /bin/bash -lc 'npm test'",
    "I have completed the evidence pass.",
    "[mcp] crew.review_record_scorecard (completed)",
    "",
    "{ \"verdict\": \"request-changes\" }",
    "Code Reviewer verdict",
    "Verdict: request-changes",
    "Required:",
    "- Remove generated bytecode files.",
    "Tests:",
    "- `npm test`: passed.",
    "CI:",
    "- Unavailable for this local PR."
  ].join("\n");

  const output = finalReviewOutput(transcript);
  assert.equal(output, [
    "Verdict: request-changes",
    "Required:",
    "- Remove generated bytecode files.",
    "Tests:",
    "- `npm test`: passed.",
    "CI:",
    "- Unavailable for this local PR."
  ].join("\n"));
  assert.doesNotMatch(output, /I'll review|\[mcp\]|\[cmd\]|Plan evidence|completed the evidence pass/);
});

test("simple review verdicts remain intact", () => {
  const output = "Verdict: approve\nRequired changes:\n- None\nTests:\n- `npm test`: passed";
  assert.equal(finalReviewOutput(output), output);
});

test("repair comments start at the final engineer summary", () => {
  const transcript = [
    "I will inspect the required findings first.",
    "[cmd] git diff --check",
    "The edit is complete.",
    "Engineer repair summary",
    "Changes made:",
    "- Removed generated files.",
    "Tests:",
    "- `npm test`: passed.",
    "Residual risk:",
    "- None."
  ].join("\n");

  assert.equal(finalRepairOutput(transcript), [
    "Changes made:",
    "- Removed generated files.",
    "Tests:",
    "- `npm test`: passed.",
    "Residual risk:",
    "- None."
  ].join("\n"));
});

test("generic final output begins after the last tool event", () => {
  assert.equal(
    finalAgentOutput("Checking evidence.\n[tool] read_file (completed)\nFinal concise answer."),
    "Final concise answer."
  );
});
