import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { agentFile } from "../src/agent-paths.js";
import { listAgentNames, loadAgentSpec } from "../src/agent-spec.js";
import { listSchedules, upsertSchedule, removeSchedule } from "../src/schedules.js";

test("v6 uses explicit agent JSON, shared defaults, and one scheduled field", (t) => {
  const root = mkdtempSync(path.join(os.tmpdir(), "crew-v6-agents-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  mkdirSync(path.join(root, ".crew/agents"), { recursive: true });
  const write = (name, value) => writeFileSync(agentFile(root, name), JSON.stringify(value));
  write("_defaults", { runner: "claude-agent-sonnet-high", reflections: false });
  write("ops", { title: "Operations", scheduled: [] });
  writeFileSync(path.join(root, ".crew/agents/notes.md"), "# Context, not an agent");
  assert.deepEqual(listAgentNames(root), ["ops"]);
  assert.equal(loadAgentSpec(root, "ops").runner, "claude-agent-sonnet-high");
  assert.equal(loadAgentSpec(root, "missing"), null, "defaults cannot invent agents");
  upsertSchedule({ targetRoot: root, schedule: { role: "ops", id: "brief", cron: "0 9 * * *", prompt: "Brief", enabled: false } });
  assert.equal(listSchedules({ targetRoot: root }).length, 1);
  assert.equal(JSON.parse(readFileSync(agentFile(root, "ops"))).scheduled[0].enabled, false);
  assert.equal(removeSchedule({ targetRoot: root, role: "ops", id: "brief" }), true);
  assert.throws(() => upsertSchedule({ targetRoot: root, schedule: { role: "missing", id: "brief", cron: "* * * * *", prompt: "Brief" } }), /JSON definition/);
  write("ops", { schedules: [] });
  assert.throws(() => loadAgentSpec(root, "ops"), /v6 uses "scheduled"/);
  writeFileSync(agentFile(root, "ops"), "{ broken");
  assert.throws(() => loadAgentSpec(root, "ops"), SyntaxError);
  assert.throws(() => agentFile(root, "../outside"), /invalid agent/);
});
